export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  headline: 'Unlimited Transactions with zero fees',
  description: 'Get access to our exclusive app that allows you to send unlimited transactions witout getting charged any fees.',
  buttonLabel: 'Get Started',
  imgStart: false,
  img: 'images/car.svg',
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
}

export const homeObjTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  headline: 'Unlimited Transactions with zero fees',
  description: 'Get access to our exclusive app that allows you to send unlimited transactions witout getting charged any fees.',
  buttonLabel: 'Learn More',
  imgStart: false,
  img: 'images/save.svg',
  alt: 'Save',
  dark: false,
  primary: false,
  darkText: true,
}

export const homeObjThree = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  headline: 'Creating an account is extremely easy',
  description: 'Get everything set up and ready in under 10 minutes. All you need to do is add your information and your\'re ready to go.',
  buttonLabel: 'Start Now',
  imgStart: true,
  img: 'images/chart.svg',
  alt: 'Data',
  dark: false,
  primary: false,
  darkText: true,
}